kind: pipeline
name: kobopatch

platform:
  os: linux
  arch: amd64

steps:
- name: deps
  image: golang:1.12.7-stretch
  commands:
  - go mod download
- name: test
  image: golang:1.12.7-stretch
  commands:
  - apt update
  - apt install -y zlib1g-dev
  - go test -v ./...
- name: cross
  image: dockercore/golang-cross:1.12.7
  commands:
  - dpkg --add-architecture i386
  - apt update
  - apt install -y libz-mingw-w64-dev zlib1g-dev:i386 zlib1g-dev libc6-dev-armhf-cross libc6-dev-i386 gcc-multilib
  - mkdir build
  - GOLDFLAGS="-linkmode external -extldflags -static -X main.version=$(git describe --tags --always)"
  - GOOS=linux    GOARCH=amd64                           CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-darwin-64bit"        ./kobopatch
  - GOOS=linux    GOARCH=amd64                           CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-apply-darwin-64bit"  ./tools/kobopatch-apply
  - GOOS=linux    GOARCH=amd64                           CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/cssextract-darwin-64bit"      ./cssextract
  - GOOS=linux    GOARCH=386    CC="gcc -m32"            CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-darwin-64bit"        ./kobopatch
  - GOOS=linux    GOARCH=386    CC="gcc -m32"            CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-apply-darwin-64bit"  ./tools/kobopatch-apply
  - GOOS=linux    GOARCH=386    CC="gcc -m32"            CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/cssextract-darwin-64bit"      ./cssextract
  - GOOS=darwin   GOARCH=amd64  CC=o64-clang             CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-darwin-64bit"        ./kobopatch
  - GOOS=darwin   GOARCH=amd64  CC=o64-clang             CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/cssextract-darwin-64bit"      ./cssextract
  - GOOS=darwin   GOARCH=amd64  CC=o64-clang             CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-apply-darwin-64bit"  ./tools/kobopatch-apply
  - GOOS=windows  GOARCH=386    CC=i686-w64-mingw32-gcc  CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-windows.exe"         ./kobopatch
  - GOOS=windows  GOARCH=386    CC=i686-w64-mingw32-gcc  CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/cssextract-windows.exe"       ./cssextract
  - GOOS=windows  GOARCH=386    CC=i686-w64-mingw32-gcc  CGO_ENABLED=1  go build -ldflags "$${GOLDFLAGS}" -o "build/koboptch-apply-windows.exe"   ./tools/kobopatch-apply
