language: go
go: 
 - "1.10"
sudo: true

script:
 - make clean
 - make build-deps
 - make deps
 - make generate
 - make test
 - make build

addons:
  apt:
    packages:
      - dos2unix

deploy:
  provider: script
  script: /bin/bash $TRAVIS_BUILD_DIR/release.sh
  skip_cleanup: true
  on:
    tags: true
branch: master